# ============================================================
# .markdownlint.yaml (Markdown linting configuration)
# ============================================================

# Disable strict line length limits
line-length: false

# Allow flexible heading styles
MD003: false   # Heading style (ATX vs Setext)
MD004: false   # Unordered list style
MD007: false   # Unordered list indentation
MD013: false   # Line length
MD022: false   # Headings surrounded by blank lines
MD024: false   # Duplicate headings
MD026: false   # Trailing punctuation in headings
MD029: false   # Ordered list item prefix
MD030: false   # Spaces after list markers
MD032: false   # Lists surrounded by blank lines
MD033: false   # Inline HTML allowed
MD034: false   # Bare URLs allowed
MD036: false   # Emphasis used instead of heading
MD040: false   # Fenced code language required

# Keep a few helpful structural rules
MD001: true    # Heading levels increment by one
MD018: true    # No space after hash in headings
MD019: true    # Multiple spaces after hash
MD041: true    # First line should be a top-level heading
